### ISSUE TITLE
Inline HTML snippet in Markdown rendered with an extra divs

### ISSUE THREAD

**Issue by okonet** [probablyup/markdown-to-jsx#101]
This snippet in the markdown document:

```md
<a href="https://opencollective.com/react-dropzone/sponsor/0/website" target="_blank"><img src="https://opencollective.com/react-dropzone/sponsor/0/avatar.svg"></a>
```

is rendered to:

![2017-04-20 at 13 43](https://cloud.githubusercontent.com/assets/11071/25229117/52b63c96-25cf-11e7-992d-27ea1f5ac8d5.png)

The `div` here is redundant and breaks the layout (I have tons of inline element that now becoming blocks)

Originally reported here: https://github.com/styleguidist/react-styleguidist/issues/402

**Comment by probablyup** [comment]
Hm why aren't you using a markdown link?

**Comment by okonet** [comment]
OpenCollective submitted a PR with this snippet so I don't want to rewrite it. Either way, this won't solve the issue with `div` and nested content.

**Comment by probablyup** [comment]
I'll take a look at this case. It's inline, so it should work. Thanks for
reporting
