### ISSUE TITLE
HTML block elements with markdown content rendered incorrectly

### ISSUE THREAD

**Issue by okonet** [probablyup/markdown-to-jsx#102]
I believe this 

```md
<div align="center">

# This is Markdown

</div>
```

should be rendered as 

```html
<div align="center">
  <h1>This is markdown</h1>
</div>
```

but it is rendered like this

```html
<div>
  <div align="center">
</div>
<h1>This is markdown</h1>
```

Reproducible on https://probablyup.github.io/markdown-to-jsx/

**Comment by okonet** [comment]
I also saw you've skipped the appropriate test in spec file. Is this a know issue? Any idea how to solve it?

**Comment by probablyup** [comment]
This is a limitation of remark. I do my best to process inline html, but
block tags are very difficult. It's also considered an antipattern to use
raw HTML in markdown, so I likely won't implement this.

**Comment by wooorm** [comment]
@okonet What’s your HTML use case?
If you’re allowing HTML in markdown on the client side, it’s essentially impossible doing it safely.

However, if you’re using it to generate some virtual dom “server-side”, you could go remark-parse -> remark-rehype - rehype-raw -> rehype-react ([something like this](https://twitter.com/sambreed/status/855995197309673473)).

**Comment by okonet** [comment]
@probablyup thanks for answering! I thought it might be a hard problem to solve since raw HTML is tricky to convert to JSX.

@wooorm thanks for chiming in. I'm building the styleguide/documentation for react-dropzone: https://react-dropzone.netlify.com from the README.md that has some HTML in it https://raw.githubusercontent.com/okonet/react-dropzone/master/README.md (scroll down to the end).

I discovered this issue then I was trying to center the logo by wrapping it and the heading with `<div align="center"></div>`

**Comment by probablyup** [comment]
One thing you could take advantage of here is markdown-to-jsx allows for
overriding the component output of particular HTML tags.

You could provide an img override that applies the centering under specific
criteria, perhaps switching on the href.

**Comment by probablyup** [comment]
Link href and/or img src I mean.
