### ISSUE TITLE
Unexpected token after 5.3.1 and 5.3.2

### ISSUE THREAD

**Issue by alansouzati** [probablyup/markdown-to-jsx#106]
After the recent update I cannot use markdown-to-jsx anymore. It complains about a loader missing. I'm assuming you guys forgot to run babel before release it?

https://github.com/grommet/grommet/issues/1330

Previous versions used index.es5.js, which does not seem to be present in the latest release from 6 hours ago.

**Comment by probablyup** [comment]
Weird, it was _definitely_ present when I published 5.3.2.

**Comment by probablyup** [comment]
<img width="709" alt="screen shot 2017-04-27 at 7 49 37 pm" src="https://cloud.githubusercontent.com/assets/570070/25508826/ac200ea2-2b82-11e7-94d9-de16c0a6c541.png">

Yeah I just did a fresh install of 5.3.2 and it's there. Not sure what to tell you.

**Comment by alansouzati** [comment]
If I install 5.3.0 it works. I didn't change anything in my code, and I installed 5.3.1 and 5.3.2. It complains about a JSX code. 

Can you double check the content of the package.json file?

**Comment by alansouzati** [comment]
![screen shot 2017-04-27 at 4 55 54 pm](https://cloud.githubusercontent.com/assets/1207250/25508976/6d6feb40-2b6a-11e7-9405-c8323494eb3e.png)


I see this warning when installing but I don't think it is related.

**Comment by probablyup** [comment]
Yeah that's a downstream thing

**Comment by probablyup** [comment]
One thing I can think of is make sure you use `yarn upgrade` to explicitly pick version 5.3.2. Just because it's in the semver range doesn't mean it'll get picked up by `yarn install` as it uses what's been pinned in the lockfile.

**Comment by alansouzati** [comment]
```
[grommet:pack]: failed
Module parse failed: /Users/alansouza/ncs-workspace/gui/node_modules/markdown-to-jsx/index.js Unexpected token (149:20)
You may need an appropriate loader to handle this file type.
|
|                 aggregator.footnotes.push(
|                     <div key={node.identifier} id={node.identifier}>
|                         {node.value || node.children.map(parser)}
|                     </div>
```

**Comment by alansouzati** [comment]
still seeing the problem. I'm not sure why `index.js` is being loaded. it should loading `index.es5.js`

**Comment by alansouzati** [comment]
it is definitely weird, I manually deleted index.js, and then everything works fine and it loads the index.es5.js.

What is the version of Node you are testing against? I'm testing with 7.3.0

**Comment by probablyup** [comment]
Oh I know what's going on. You're probably using webpack2, which pays attention to the "module" field. I added that recently, only had "jsnext:main" before. Give me a few.

**Comment by alansouzati** [comment]
no problem, glad you figure out what is going on

**Comment by alansouzati** [comment]
and yes, I'm using webpack2

**Comment by probablyup** [comment]
@alansouzati try 5.3.3

**Comment by alansouzati** [comment]
it works, as always thanks for the quick follow-up

**Comment by probablyup** [comment]
Excellent!
