### ISSUE TITLE
closing tag recognised as an opening tag

### ISSUE THREAD

**Issue by Haroenv** [probablyup/markdown-to-jsx#107]
see in this [codesandbox](https://codesandbox.io/s/v2GDLnlp8):

```markdown
<details>
<summary><strong>Table of Contents</strong></summary>

- [Contributing](#contributing)
</details>
```

is rendered with two `details` tags

```html
<details>

<summary><strong>Table of Contents</strong></summary>

- [Contributing](#contributing)

</details>
```

Renders better, but still has issues with the summary tag.

This can also be tested in the demo site 😄

**Comment by probablyup** [comment]
I'll take a look, thanks!

**Comment by probablyup** [comment]
I have a feeling this issue is because I don't have `details` in the block tags whitelist at the top of index. Very simple to add though, will try it tonight if I have time.

**Comment by Haroenv** [comment]
I just updated the sandbox to add `details` to the block tag whitelist, which helps in a way, but not completely: 

https://codesandbox.io/s/v2GDLnlp8

before change|after change
---|---
<img width="432" alt="screen shot 2017-06-20 at 14 37 21" src="https://user-images.githubusercontent.com/6270048/27333407-0f55bbda-55c6-11e7-8356-1677b3e78d83.png">|<img width="373" alt="screen shot 2017-06-20 at 14 37 02" src="https://user-images.githubusercontent.com/6270048/27333408-0f73e06a-55c6-11e7-86bb-d0082337d619.png">

**Comment by probablyup** [comment]
And summary- to be fair remark (the parser library under this one) also
maintains its own version of the whitelist I think so may need to send a PR
there as well.

**Comment by Haroenv** [comment]
adding summary didn’t change anything, I tried it as well
