### ISSUE TITLE
html does not get custom tags

### ISSUE THREAD

**Issue by Haroenv** [probablyup/markdown-to-jsx#108]
```jsx
<Markdown
  options={{
    overrides: {
      img: {
        component: GitHubImage,
      },
      a: {
        component: GitHubLink,
      },
    },
  }}
>
  {this.state.text}
</Markdown>
```

These overrides aren’t called when a literal html element is used, or if it’s part of another html element.

**Comment by probablyup** [comment]
Hi there, could you post some more of your code so I can see what's
happening? Particularly the implementations for the two custom components.

**Comment by Haroenv** [comment]
Also visible on https://codesandbox.io/s/v2GDLnlp8

It’s easily visible in the table that contains images

**Comment by probablyup** [comment]
Sorry it took a bit to get back to you on this - basically since remark opts out of converting HTML into the equivalent AST entities, there's not much I can do without implementing my own HTML->JSX parser... which is a bit out of scope for what this library is meant to do.
