### ISSUE TITLE
Override nested html elements with single custom component?

### ISSUE THREAD

**Issue by pcmaffey** [probablyup/markdown-to-jsx#112]
Wondering if it's possible to override groups of html elements? For instance, right now I have:

```
  p: {
       component: P,
      },
  img: {
       component: Image,
      },
```
Because everything seems to get wrapped by `<p>`, this outputs` <P><Image></P>`
Can I define an override for `<p><img></p>` to produce a single component `<Image>`?
Something like: 

```
  p: {
       component: P,
       img: {
               component: Image,
               },
      }
```

**Comment by probablyup** [comment]
Hey there! Not at present, no. What you could do though is define a paragraph override component that inspects its direct child(ren) and render an image instead, conditionally.

**Comment by wesleyguirra** [comment]
Any news on this, need same functionality
