### ISSUE TITLE
Add ability to customise html wrapper

### ISSUE THREAD

**Issue by theetrain** [probablyup/markdown-to-jsx#113]
I noticed all compiled markdown is wrapped in a `<div>` element here: https://github.com/probablyup/markdown-to-jsx/blob/9c16391d7722942e43ffa7e2b079189c3c3d84f3/index.js#L486-L490

I'd like to be able to override `<div>` with my own JSX object. I can help develop this feature if you like.

**Comment by probablyup** [comment]
Hey there, sorry it took a bit to get back to you.

The bit of code you referenced is only for arbitrary block-level HTML found inside markdown files. However, regular markdown is also wrapped in a "root" `<div>` if there are multiple blocks; that code exists here: https://github.com/probablyup/markdown-to-jsx/blob/master/index.js#L261-L262

Could you explain your use case in more detail? We could certainly add the functionality, but I'm curious what you need it to accomplish.

**Comment by theetrain** [comment]
Here is some more background: I'm using react styleguidist to document some in-house components, and I'm dogfooding the components within the documentation's markdown overrides. For example, I'm overriding `<strong>` elements with my own `<Strong />` component. Since sections of elements are wrapped with a div, I created my own `<Box />` component that has a bottom margin of 16px to get my desired spacing. However, the line of code I referenced in my previous post outputs a `<div>` that I cannot override with my component.

**Comment by probablyup** [comment]
This is coming in https://github.com/probablyup/markdown-to-jsx/pull/115

**Comment by probablyup** [comment]
Fixed in v6!

**Comment by pcmaffey** [comment]
@probablyup I don't see where this option can be set in the API? Would love to replace root wrapping <div> with <React.Fragment>...

**Comment by probablyup** [comment]
@pcmaffey hmm I think the wrapper override functionality might have gotten lost during the refactor. What I might just do is require React 16.3+ in v7 and wrap with a fragment by default so the wrappers don't need to exist at all.

**Comment by tb** [comment]
I have a case when I use Markdown to render formatted h1 content (for highlights with `Imporatant **keyword** in title`)

With code:

```
        <h2>
          <Markdown
            options={{
              forceInline: true,
              overrides: {span: Fragment, p: Fragment},
            }}
            children={project.subtitle}
          />
        </h2>
```

It renders:

```
<h2><span>Imporatant <strong>keyword</strong>in title</span></h2>
```
