### ISSUE TITLE
Prettier-generated tables are not supported

### ISSUE THREAD

**Issue by sapegin** [probablyup/markdown-to-jsx#133]
This code renders fine:

```md
Foo | Bar
-|-
1 | 2
```

But if you [run Prettier](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAxCEAEAfTAhAQwCcAdKAWm3LIEYdMAmEAGhAgAcYBLaAZ2VDEiEAO4AFYgn4oWIArxjIAZgQA2vOKwBGRAmADWcGAGV2erlADmyGEQCumkABMIYZWo2sLGojDG7LAFsCd3VHACteAA88XQMjYwJAuAAZCzhQzzY7GHYcpiQVMNYzIh9kEGCifRcRKFl2IgsYAHUuJxgAC2QADgAGEuENFt12Csa4HwA3DNYiOABHOy55-wIgkMKPRw1Arht7HYtLVTgARTsIeEzHGAItNo7upAZWWwIuVWOAYQhA4IqUGgsxAdg0ABV7tIihoAL6woA), it will generate this code, and it doesn’t work:

```md
| Foo | Bar |
| --- | --- |
| 1   | 2   |
```

Actually, this still works:

```md
| Foo | Bar |
- | -
| 1 | 2 |
```

But this doesn’t:

```md
| Foo | Bar |
| - | - |
| 1 | 2 |
```

**Comment by sapegin** [comment]
I see that simple-markdown has two kinds of tables: `table` and `nptable`. Prettiefied example works with `table`.

**Comment by probablyup** [comment]
Tables definitely work, there’s a test for them. Might be a formatting
issue.

**Comment by sapegin** [comment]
@probablyup I’ve updated the issue with a correct description.

**Comment by probablyup** [comment]
I’ll double check this. My guess is the “block markdown” regex needs a
tweak.

**Comment by probablyup** [comment]
got it in 9a3994d
