### ISSUE TITLE
Multiple lines of BR tags are locking browser (crash)

### ISSUE THREAD

**Issue by michaelryancaputo** [probablyup/markdown-to-jsx#136]
Version: 6.3.0
Reproducible by trying to parse the below html (confirmed in stackblitz, this will crash your browser tab: https://stackblitz.com/edit/react-obc3tp)

Content editors are crazy, and somehow they made this break by putting too many BR tags.

      $25
      <br>
      <br>
      <br>$50
      <br>
      <br>
      <br>$50
      <br>
      <br>
      <br>$50
      <br>
      <br>
      <br>

Confirmed this is not an issue on the package, in version `5.4.2` (https://stackblitz.com/edit/react-5ra1sd)

**Comment by probablyup** [comment]
👍 will look into it probably tomorrow night
