### ISSUE TITLE
Incorrect table rendering

### ISSUE THREAD

**Issue by AwK55** [probablyup/markdown-to-jsx#138]
Hi there, markdown tables is rendered incorrect even on your demo here. 
![image](https://user-images.githubusercontent.com/11617476/34262321-2336e1ae-e67d-11e7-89d6-043b1cc05e8c.png)

Parser add extra children in table's children. How it can be resolved?

**Comment by probablyup** [comment]
Probably just a tweak in a regex. I’ll take a look tonight or tomorrow
