### ISSUE TITLE
Support for self-closing tags

### ISSUE THREAD

**Issue by Planeshifter** [probablyup/markdown-to-jsx#140]
Thank you for this promising library, very useful indeed!

I have noticed that self-closing tags for React components are currently not parsed correctly when they span multiple lines.

While 

```jsx
<DatePicker biasTowardDateTime="2017-12-05T07:39:36.091Z" timezone="UTC+5" />
```

is correctly parsed, 

```jsx
<DatePicker 
    biasTowardDateTime="2017-12-05T07:39:36.091Z" 
    timezone="UTC+5" 
/>
``` 
is not. This is the case no matter how the JSX attributes are indented.

**Comment by Andreyco** [comment]
I experience different issue with self closing tags.

```jsx
// Good
<br />

// Bad
<br/>
```

As you can see, space is required before `/>` characters.

**Comment by probablyup** [comment]
Will take a look thanks
