### ISSUE TITLE
Parsing of JSX attributes

### ISSUE THREAD

**Issue by Planeshifter** [probablyup/markdown-to-jsx#141]
It would be great if attributes were correctly parsed not only for just simple HTML attributes, but JSX attributes such as those in the following examples:

```jsx
<MyComponent times={12}>Isn't that cool?</MyComponent>

<MyComponent arr={[1,2,3]}>Isn't that just as cool?</MyComponent>

<MyComponent onChange={function(){
    // Handle changes...
}}>Isn't that very cool?</MyComponent>

<MyComponent obj={{
  'firstName': 'Evan'
  'lastName': 'Scott'
}}>Isn't that the coolest?</MyComponent>
```

**Comment by probablyup** [comment]
Hmm this would be very hard to achieve without use of eval() which would
break security.

**Comment by probablyup** [comment]
My recommendation is to define each variant you want statically with an HOC
like recompose’s withProps() and name them differently.

Otherwise, provide the props as strings and parse them in your custom
component. I could probably hack in number support as well.

**Comment by Planeshifter** [comment]
Thanks for your recommendations! I consider this issue closed.
