### ISSUE TITLE
Code blocks produce null children prop

### ISSUE THREAD

**Issue by hugmanrique** [probablyup/markdown-to-jsx#144]
I have a Markdown file which contains the following:

```ruby
['a', 'b'].map { |x| x.uppercase }
```

By using `require('markdown-to-jsx').compiler('<String above>', {})` I'm getting the following JS output:

![Chrome console output](https://i.imgur.com/n4tcD15.png)

As you can see, the second children in that array has a `null` children instead of the code above. Even though I haven't installed `highlight.js`, it is being packaged by Webpack.

Single quoute fences also have empty outputs. I'm using version `6.4.0` and React `16`.

**Comment by probablyup** [comment]
> Single quote fences

I don't think that's a valid GFM syntax. Code fences must always be three backticks.

Also, this is working for me:
```
```rb
['a', 'b'].map { |x| x.uppercase }
\```
```

(ignore the escape, needed it so I could put the fence in a fence on github, heh)

**Comment by hugmanrique** [comment]
What I meant with single quote fences are these: `hello`, which are made with `.

Is the compile function used internally or does it use another method?

**Comment by probablyup** [comment]
Yeah, it's used internally. Hmm... I wonder what the issue could be. That all works fine in React 15.x...

**Comment by hugmanrique** [comment]
Found the issue, it was something to do with how I handle the compile output. Sorry for the spam 😬
