### ISSUE TITLE
Table produces thead and tbody elements with "null" keys

### ISSUE THREAD

**Issue by hugmanrique** [probablyup/markdown-to-jsx#145]
I have a Markdown document with the following table:

```markdown
| ID  | Name               | Rank              |
| --- | ------------------ | ----------------- |
| 1   | Tom Preston-Werner | Awesome           |
| 2   | Albert Einstein    | Nearly as awesome |
```

And it's producing the following React output:

![Chrome console output](https://i.imgur.com/bi3Dhec.png)

As you can see instead of having an integer key (like all the other elements), both elements have a "null" key. Versions: same as #144

**Comment by probablyup** [comment]
Hmm ok. Is that breaking things for you? I tried your sample out on the demo site and it seems to work okay.

**Comment by hugmanrique** [comment]
Yeah, React doesn't allow having duplicated keys under the same parent. There must be something wrong with the versions I'm using or how I'm calling the compile method...

**Comment by probablyup** [comment]
The demo site uses Preact, so it's possible Preact is more lenient about the keys... I'll try and figure it out either tonight or this weekend. Thanks for the report 👍

**Comment by hugmanrique** [comment]
Nvm, found the problem. It was an issue with how I was handling the compile output. Sorry for the spam 😄
