### ISSUE TITLE
Use special chars like &gt; ,  \u00b7 or <

### ISSUE THREAD

**Issue by smussell** [probablyup/markdown-to-jsx#151]
Is there anyway to embed special chars into the markdown text outside of a code block?

I've tried a few things, wrapping in brackets, using the < char directly, wrapping in quotes, etc, but I can't find anyway to make it render correctly.

Thanks

**Comment by probablyup** [comment]
You should be able to escape with a backslash I think?

**Comment by probablyup** [comment]
@smussell can you close if backslashing works for you? Otherwise I'll close this in a week.

**Comment by smussell** [comment]
Thanks, sorry for delayed followup.  The backslash didn't work, but I got it to work by using `<span><</span>`.
