### ISSUE TITLE
Render Markdown in HTML

### ISSUE THREAD

**Issue by pravdomil** [probablyup/markdown-to-jsx#153]
Hello, is there any chance to get Markdown syntax working inside HTML elements?

Now this
```md
<div style="float: right">

# Hello

</div>
```

renders as `<div style="float: right;"># Hello</div>`

I know that some md compilers does it and some not, but can we do that with passing some option to compiler?

**Comment by probablyup** [comment]
Hmm, you mean using the compiler in this library for all `createElement` if the sole child is a string?

**Comment by probablyup** [comment]
Ah nvm I understand. This appears to be a bug.

**Comment by probablyup** [comment]
Looking into this further, it's a tough one. We're currently parsing the contents of html blocks as inline unless another HTML tag is detected. If we change that behavior, the whitespace of the HTML starts to matter.

For instance, if a nested HTML tag has 4 spaces in front of it, that technically makes it an [indented code block](https://github.github.com/gfm/#indented-code-blocks). Things get progressively more complex from there with the various edge cases and now having to start being aware of what whitespace is worth paying attention to and what should be discarded...

**Comment by pravdomil** [comment]
> my inclination is to leave things as-is

you meant leave it to render 4 space indents as code blocks?

**Comment by probablyup** [comment]
Yup. You can see the PR I made which fixes this use case, but it just introduces a new edge case of intentional indented code blocks not working inside HTML since we have to choose. 

That being said, I’m open to merging the PR since HTML in markdown is a hack as-is and just add a note somewhere describing caveats.

**Comment by pravdomil** [comment]
yes that's what I would do

**Comment by ivan-kleshnin** [comment]
Is there a way to disable this behavior? I need the MD syntax to stay untouched inside my component:

```
<MyOwnSyntax>
  * Foo
  * Bar
  * Baz
  
  **test**
</MyOwnSyntax>
```

**Comment by probablyup** [comment]
Use a fenced code block

**Comment by ivan-kleshnin** [comment]
Each of them will add two lines to MD content. And I'll have multiple cases like this per file:

```
<Quiz>
* Option-1
* Option-2
* Option-3
</Quiz>

<Quiz>
* Option-1
* Option-2
* Option-3
</Quiz>
```

vs this:

```
<Quiz>
'''
* Option-1
* Option-2
* Option-3
'''
</Quiz>

<Quiz>
'''
* Option-1
* Option-2
* Option-3
'''
</Quiz>
```

– quite a burden.

**Comment by probablyup** [comment]
It’s markdown in a markdown processor, not sure what to tell you. Putting
it in a code block is the only way to tell the compiler it’s not meant to
be processed.
