### ISSUE TITLE
Line of text w/o line break wraps with span instead of P

### ISSUE THREAD

**Issue by michaelryancaputo** [probablyup/markdown-to-jsx#166]
Having an issue where a string of text within the Markdown component that does not contain a line break gets wrapped with a `<span>` tag instead of what I would expect a `<p>` tag.

I took some screen shots highlighting the text from your demo site, you'll notice the one with the line break produces a P tag, the other does not.

![screen shot 2018-03-26 at 9 59 30 am](https://user-images.githubusercontent.com/80901/37920829-cb63b808-30dc-11e8-8241-418ab1dd4fdf.png)

![screen shot 2018-03-26 at 9 59 42 am](https://user-images.githubusercontent.com/80901/37920833-ce1d63fa-30dc-11e8-9d57-ac844eda0e79.png)

I would expect that any string, even if it doesn't contain a line break would be wrapped in a P tag unless a markdown or html modifier is supplied. I believe this is how Markdown is supposed to behave.

**Comment by michaelryancaputo** [comment]
I just noticed there is a new option to `forceBlock`. Looking into this as a fix, it appears to.

**Comment by probablyup** [comment]
@michaelryancaputo ah yes this is by design. The way you'd get around it is to put a padding newline at the end of the content, or use the `forceBlock` option as you found

**Comment by probablyup** [comment]
I might end up removing this distinction though in v7 since a lot of people get tripped up by it. The goal was to avoid wrapping with `<p>` if everything inside was inline syntax.

**Comment by michaelryancaputo** [comment]
Yeah, totally get why you did that, but it is kind of unintuitive and doesn't behave as you would expect. I'm going to close this as the option seems to have fixed my issue (RTFD!).

Thanks again!

**Comment by probablyup** [comment]
https://github.com/probablyup/markdown-to-jsx/pull/167
