### ISSUE TITLE
Potential enhancement - Allow className prop directly on Markdown component

### ISSUE THREAD

**Issue by JonShort** [probablyup/markdown-to-jsx#171]
First, thanks for this library, the docs & api are excellent 👍.

### The feature
Allow a `className` prop to be added to the `<Markdown />` component directly.

e.g.
```jsx
<Markdown className="myClass">
  {markdownText}
</Markdown>
```

### Reasons / use-case
I have a use-case where i need to apply specific styling to anchors which are telephone links e.g. 
```html
<a href="tel:+123456789" />
```

My ideal approach would be to create a styled component of the `<Markdown />` component, e.g. 
```js
const modifiedMarkdown = styled(Markdown)`
  a[href^=tel] {
    myStyles
  }
`;
```

This would allow me to retain the default styling of non-telephone anchors.

Unfortunately for styled-components to style the Markdown component, it needs to pass a className prop down directly;

### Tackling the use-case without the className prop
There are ways to handle this use-case where it happens, although they require a lot of abstraction, I've made a codesandbox to show this - [https://codesandbox.io/s/mzo4mw6q89](https://codesandbox.io/s/mzo4mw6q89)

### Conclusion
There are a number of ways to handle this use-case with the component as-is (including adding a div wrapper with this css attached) so i'll leave this at the maintainers' discretion.

Thanks for your time 👍

**Comment by probablyup** [comment]
Totally makes sense, I’d love to pass along all normal DOM attributes to
the wrapper in general.

**Comment by probablyup** [comment]
Added in `6.6.2`, thanks for reporting!

**Comment by JonShort** [comment]
Awesome! I've been on holiday so only just seeing this now - thanks for your effort 🎉
