### ISSUE TITLE
Allow non  alphanumeric characters id for headings

### ISSUE THREAD

**Issue by yo7** [probablyup/markdown-to-jsx#177]
Currently, `markdown-to-jsx` generates HTML with ID for headings. like:

```markdown
# This is Markdown
```

This markdown is converted to following HTML.

```html
<h1 id="this-is-markdown" class="">This is Markdown</h1>
```

But, non  alphanumeric characters like Japanese headings are converted to HTML tags with empty id.

```markdown
# これはマークダウンです
```

```html
<h1 id="" class="">これはマークダウンです</h1>
```

But it's inconvenient and I want heading tag with Japanese characters to have id.
I think this can be achievable by changing the logic to replace accented characters:

https://github.com/probablyup/markdown-to-jsx/blob/3a1e9d27db4f96ff017e15265a5dedc6a2f9baa5/index.js#L226

To be more specific, you can encode non alphanumeric characters and set its value to id.

You can encode Japanese using `encodeURIComponent()` funcation and `(encodeURIComponent("これはマークダウンです")` returns `"%E3%81%93%E3%82%8C%E3%81%AF%E3%83%9E%E3%83%BC%E3%82%AF%E3%83%80%E3%82%A6%E3%83%B3%E3%81%A7%E3%81%99"` (ref: https://stackoverflow.com/questions/18656089/japanese-characters-escape-and-decoding-in-js)

So, example above(html tag with empty id) can be:

```html
<h1 id="%E3%81%93%E3%82%8C%E3%81%AF%E3%83%9E%E3%83%BC%E3%82%AF%E3%83%80%E3%82%A6%E3%83%B3%E3%81%A7%E3%81%99" class="">これはマークダウンです</h1>
```

This would be useful for  non-alphanumeric language speakers like me. For example, I would need this to implement TOC.

**Comment by probablyup** [comment]
Sounds cool to me, would you be open to sending a PR?

**Comment by yo7** [comment]
Thanks. Yes, I'll send a PR when I have time!
