### ISSUE TITLE
Error parsing < and >

### ISSUE THREAD

**Issue by niallel** [probablyup/markdown-to-jsx#180]
Hi,

When I use angle brackets in certain situations I get 
InvalidCharacterError: The string contains invalid characters.

In the following if I use 1<2 (with no space between the < and 2) then I get the InvalidCharacterError:
`<Markdown>
{'1<2 or 2>1'}
</Markdown>`

If I put a space after the < it will work.
`<Markdown>
{'1< 2 or 2>1'}
</Markdown>`

This is what happens when the first character after the < is a number.

If it was another character then the output is displayed wrong. For example
`<Markdown>
{'1<a or 2>1'}
</Markdown>`
Will display:
**11**
missing everything between and including the <>

Now I understand I should be passing 
`&lt;` or `&gt;` but when I pass those values they aren't translated to < or >, they just display as `&lt;` or `&gt;`.

Is there a problem here, or being stupid and not doing something?

thanks,

**Comment by probablyup** [comment]
Yuck, looking into this. Thanks for reporting.

**Comment by probablyup** [comment]
Fix is out in `6.6.6` thanks! https://github.com/probablyup/markdown-to-jsx/releases/tag/6.6.6

**Comment by niallel** [comment]
Thanks so much, it fixes the first issue but it doesn't fix the second issue.

When there is 
`<Markdown>{'1<a or 2>1'}</Markdown>`
It will be output as
11

Any ideas?

**Comment by probablyup** [comment]
That one is more difficult to solve; will have to think more on it.

The problem is it is being detected as an `<a>` tag and then probably thrown out on render since the syntax is invalid, resulting in `11`. We don't validate individual attribute groups at HTML detection time or do any enforcement of self-closing vs normal html syntax to save on library size (would introduce a fair amount of code.)

**Comment by niallel** [comment]
Maybe allow 
`&gt; &lt; `
to be displayed correctly.

At the moment if you pass `<Markdown>{'&gt;'}</Markdown>` then `&gt;` will be shown.

If you parsed those and displayed as > < then you wouldn't need to worry about this.

**Comment by probablyup** [comment]
Yes but one of the important parts of this library is supporting the html
syntax. So if I did that, the html wouldn’t work. This is just an edge case
to be overcome

**Comment by niallel** [comment]
Thanks, I completely understand your reasoning.

Maybe its my understanding, but `&gt;` gets displayed correctly by the browser as >
But when its inside <Markdown> the browser doesn't render it correctly.

I've worked around it by putting spaces around < or > as there shouldn't be any HTML in my input, just curious as to why when I pass in &gt; it doesn't get shown correctly.
