### ISSUE TITLE
`<figure>` children wrapped in `<p>`

### ISSUE THREAD

**Issue by coreyward** [probablyup/markdown-to-jsx#181]
When I use markdown like the following, markdown-to-jsx wraps the children of the `<figure>` element in a paragraph tag:

```
<figure>
  ![](//placehold.it/300x200)
  <figcaption>This is a placeholder image</figcaption>
</figure>
```

Output (formatted for readability):

```html
<figure>
  <p>
    <img src="//placehold.it/300x200">
    <figcaption>This is a placeholder image</figcaption>
  </p>
</figure>
```

This is invalid and React complains about it: 

```
Warning: validateDOMNesting(...): <figcaption> cannot appear as a descendant of <p>.
    in figcaption (created by Markdown)
```

**Comment by probablyup** [comment]
Released in 6.6.6 thanks :) https://github.com/probablyup/markdown-to-jsx/releases/tag/6.6.6

**Comment by coreyward** [comment]
Hey @probablyup, it looks like this change also prevents adding `<p>` tags to any child content, like that of a `<blockquote>` or `<div>` custom element (e.g. I have an `<intro>` that gets overridden by a custom React component that renders a div; the children used to be `<p>` tags, but now the newlines between the content paragraphs are removed entirely).

**Comment by evan-scott-zocdoc** [comment]
Please make a separate issue with a repro case, thanks
