### ISSUE TITLE
Underscores in emphasized text break output

### ISSUE THREAD

**Issue by klaemo** [probablyup/markdown-to-jsx#188]
Hey,
thank you for this great library!

I've noticed an issue with URLs containing `_` in `href`s of links inside of `<em>`s:

```js
const md = '*This is emphasized text with [a link](https://example.com/asdf_asdf.pdf), and another [link](https://example.com).*'
const element = compiler(md)
```
outputs
```html
<span>
  <em>This is emphasized text with [a link](
    <a href="https://example.com/asdf">https://example.com/asdf</a>
  </em>asdf.pdf), and another
  <a href="https://example.com">link</a>.*
</span>
```
(indentation added manually for better readability)

My guess is that because `_` also terminates emphasis in markdown the parser gets confused.
Let me know if you need any more information!

Thanks!

**Comment by probablyup** [comment]
I'll take a look, thanks!

**Comment by probablyup** [comment]
Should be fixed in https://github.com/probablyup/markdown-to-jsx/releases/tag/6.6.8

**Comment by klaemo** [comment]
Awesome! 🥇 Thank you so much! 🙏  I can confirm that the problem is fixed!
