### ISSUE TITLE
Is that possible to swap <a> with <Link> component from react-router?

### ISSUE THREAD

**Issue by leoyli** [probablyup/markdown-to-jsx#191]
Hi,

I'm trying to swap all my `<a>` HTML tag with `<Link>` component from **react-router**... But how can I pass `href` attribute to `to` prop?  In other words, how do I access the attribute value in markdown and pass it as the prop? Or I have to not to use `[]()` syntax an just use `<Link>` in my markdown string?

Thanks!

**Comment by probablyup** [comment]
Ah, so you'd want to do something like this:

```jsx
const LinkWrapper = ({ href, ...props }) => <Link to={href} {...props} />;

overrides: { a: LinkWrapper }
```

**Comment by leoyli** [comment]
Oh I see, I now understand the override part in the manual.  Basically I just treat HTML as component in the overrides option.  Maybe a small update on the doc may help other people?!  Thanks though!

**Comment by esteves67** [comment]
> ```js-jsx
> const LinkWrapper = ({ href, ...props }) => <Link to={href} {...props} />;
> 
> overrides: { a: LinkWrapper }
> ```

@probablyup is it possible to replace <code> with <strong> ? If yes, how to do it? Thank you !!! :heart:

**Comment by esteves67** [comment]
> Ah, so you'd want to do something like this:
> 
> ```js-jsx
> const LinkWrapper = ({ href, ...props }) => <Link to={href} {...props} />;
> 
> overrides: { a: LinkWrapper }
> ```

Is it possible to replace `<code>` with `<strong>` ? If yes, how to do it? Thank you so much !!! :heart:

**Comment by esteves67** [comment]
> Ah, so you'd want to do something like this:
> 
> ```js-jsx
> const LinkWrapper = ({ href, ...props }) => <Link to={href} {...props} />;
> 
> overrides: { a: LinkWrapper }
> ```

@probablyup Is it possible to replace `<code>` with `<strong>` ? If yes, how to do it? Thank you so much !!! :heart:
