### ISSUE TITLE
Conflict with TRIM_HTML and DETECT_BLOCK_SYNTAX

### ISSUE THREAD

**Issue by maarekj** [probablyup/markdown-to-jsx#196]
Hi, I have a feeling there's a conflict between `TRIM_HTML` and `DETECT_BLOCK_SYNTAX`

`TRIM_HTML` deletes the leading spaces.

`DETECT_BLOCK_SYNTAX` checks it if there are not **2 spaces together** at the beginning of the line (which means a line break).

It is therefore impossible to create a custom component that simply contains text with line breaks (and paragraph), because the leading spaces are removed by `TRIM_HTML`, before being processed by `DETECT_BLOCK_SYNTAX`

I propose to add a `childrenType` option to our custom components:
for example:

```jsx
<Markdown
  children={md}
  options={{
    overrides: {
      CustomComp: {
        component: CustomComp,
        childrenType: 'block' // or 'inline' or 'auto'
      },
    },
  }}
/>
```

**Comment by probablyup** [comment]
I changed this code a lot today, so probably worth checking it out again cc3397ce1bab8afbc982c4dcc47b17b00c5cb4aa

**Comment by probablyup** [comment]
The demo site should be updated, or feel free to pull down the new 6.7.1
