### ISSUE TITLE
Detect space before underscore

### ISSUE THREAD

**Issue by karatechops** [probablyup/markdown-to-jsx#200]
I'm currently using this library for [grommet-swagger](https://github.com/grommet/grommet-swagger), its often there are strings such as `object_cluster_id` which should not trigger an em. I'm going off Github's Markdown flavor but I thought a space needs to be present before and after the underscore to style the component.
For example: 
`this_shouldnt_em` = this_shouldnt_em 
`this _should_ em` = this _should_ em

**Comment by probablyup** [comment]
I don’t think that’s true. I recommend putting an inline code block around
those strings with single backticks.

**Comment by karatechops** [comment]
After digging into the spec a bit  -
> Many implementations have also restricted intraword emphasis to the * forms, to avoid unwanted emphasis in words containing internal underscores. (It is best practice to put these in code spans, but users often do not.)

> internal emphasis: foo\*bar*baz
no emphasis: foo_bar_baz

Would it be possible to handle disabling intraword emphasis via underscore with passing a prop to the Markdown component? the parsing happens before any overrides so I'm not sure this can be done.

**Comment by probablyup** [comment]
I’d really rather not. It’s a much better idea just to enclose those pieces
of code with code spans. They are symbols anyway so it makes sense to do
this in the first place.

**Comment by karatechops** [comment]
Makes sense
