### ISSUE TITLE
Is it possible to access inner contents of element as it was written in md?

### ISSUE THREAD

**Issue by jonearley** [probablyup/markdown-to-jsx#201]
I'm building a documentation site for a pattern library and would like to write code examples in markdown and then render it with a live code editor like [react-live](https://react-live.kitten.sh/).

```md
## Start now button

Launch your service with a Start now button.

<Example>
  <Button kind="start">Start now</Button>
</Example>
```

And have it render out something like this:

<img width="693" alt="screen shot 2018-08-03 at 12 29 43 pm" src="https://user-images.githubusercontent.com/1678665/43654445-3b0c19fa-9719-11e8-9661-22b4e77d0d8d.png">

The missing piece is having the "children" of `<Example>` passed through as a string so that `react-live` can handle rendering.

**Is it possible to access the inner contents of `<Example>` as it is written in the markdown?**

**Comment by probablyup** [comment]
Oh definitely! Make an override function for “Example” and then handle the
children as desired.

**Comment by jonearley** [comment]
Thanks for the response!

The code below generates the screenshot above. My issue with this override is that I don't know how to get the inner contents of <Example> as it was written in the markdown. The children are already React elements at this point.

```js
const ExampleOverride = ({ children, ...props }) => {
  return (
    <Example code={`<Button kind="start">Start now</Button>`} />
  )
}
```

The example expects a code prop of valid JSX.

**Comment by probablyup** [comment]
Oh I see. Hmm yeah it’s not currently possible to grab that, but it could
be added as it’s available during the “react” step of each rule.

**Comment by jonearley** [comment]
If it could be added that would make amazing! I'll look to publish a companion library for live code examples in markdown.

Curious -- Have you come across other approaches to including live code examples in markdown?

**Comment by probablyup** [comment]
I think react-styleguidist does it?

**Comment by jonearley** [comment]
```js
export default function Markdown({ children, options, ...props }) {
    return React.cloneElement(compiler(children, options), props, children);
}
```

Would something like this be the right idea? Thinking of forking.

https://github.com/probablyup/markdown-to-jsx/blob/master/index.js#L1584

**Comment by probablyup** [comment]
Well that would clone the whole tree for you. Are you looking to obtain the entire markdown block source or just whatever is inside a specific rendered HTML element/component?

**Comment by jonearley** [comment]
Gotcha. For this just interested in whatever is inside the specific rendered HTML element/component.

**Comment by jonearley** [comment]
This is the kind of doc experience I'm aiming for: https://github.com/emotion-js/emotion/blob/master/docs/css.md.

Looks like I'll be trying out Gatsby next.
