### ISSUE TITLE
Markdown parser doesn't support hard tabs for indentation

### ISSUE THREAD

**Issue by EvHaus** [probablyup/markdown-to-jsx#202]
**Current behavior**

When adding custom sections (as markdown files). the markdown parser doesn't seem to support tabs. So the following content:

```
Here is a list

* One
	* Two
		* Three
```

Is not rendered in a nested fashion. However, converting tabs to 4 spaces, fixes the issue.

**To reproduce**

```
// styleguide.config.js
{
	sections: [{
		content: 'README.md',
	}]
}

// README.md
Here is a list

* One
	* Two
		* Three
```

**Expected behavior**

Currently renders lists as:

![screen shot 2018-08-10 at 3 37 03 pm](https://user-images.githubusercontent.com/226640/43984103-40743cb6-9cb3-11e8-8f1c-043420c91461.png)

Should render as:

![screen shot 2018-08-10 at 3 37 21 pm](https://user-images.githubusercontent.com/226640/43984110-4c112a52-9cb3-11e8-8a12-59da5859e4a5.png)

Originally logged here: https://github.com/styleguidist/react-styleguidist/issues/1085

**Comment by probablyup** [comment]
Will take a look today probably

**Comment by probablyup** [comment]
It's working on the demo site...

**Comment by EvHaus** [comment]
My bad. Looks like this isn't an issue with `markdown-to-jsx`. I'm experiencing this issue with `react-styleguidist` which uses `markdown-to-jsx` under the hood, but after adding some tracing steps, it looks like there's a bug somewhere else that sends invalid markdown to the parser.

It's stripping out tabs and converting them to spaces. Will log an issue with them instead.

**Comment by probablyup** [comment]
Ok great, no problem! Glad to see it wasn't me 😆
