### ISSUE TITLE
Code indents in code blocks between HTML tags

### ISSUE THREAD

**Issue by AlexanderPrendota** [probablyup/markdown-to-jsx#203]
Hello!

REPRODUCED ONLY: code block MUST BE between HTML blocks.

![2018-08-16 10_22_07](https://user-images.githubusercontent.com/10503748/44194296-40159280-a13e-11e8-9561-1e2d93ec8ad2.gif)

Example block:

```md
<div>
`​`​`kotlin
fun main(args: Array<String>) {
     print("Hello world")
}
`​`​`
</div>
```

render as:

```md
<code>
fun main(args: Array<String>) {
print("Hello world")
}
</code>
```

**Comment by probablyup** [comment]
I think it's the same issue with ZWSP here. If I type it fresh it works.

**Comment by AlexanderPrendota** [comment]
@probablyup Hello! Any updates on [I-205]? Could you take a look, please? Thanks. =)

**Comment by probablyup** [comment]
@AlexanderPrendota So we need to trim in most cases because if you write your HTML with any sort of normal indentation, that indentation will then probably be detected as a blockquote.

**Comment by probablyup** [comment]
Should work after cc3397ce1bab8afbc982c4dcc47b17b00c5cb4aa - will put out a patch soon

**Comment by AlexanderPrendota** [comment]
@probablyup Awesome! Thank you so much 🎉
