### ISSUE TITLE
Horizontal rulers (----) aren't supported if preceded by a list

### ISSUE THREAD

**Issue by EvHaus** [probablyup/markdown-to-jsx#204]
The following markdown:

```markdown
- some
- list

----
```

Is generated as:

```html
<ul>
    <li>Some</li>
    <li><p>List</p></li>
    <li>
        <ul>
            <li>*</li>
        </ul>
    </li>
</ul>
```

Whereas I was expecting this:

```html
<ul>
    <li>Some</li>
    <li><p>List</p></li>
</ul>
<hr />
```

Sidenote (unrelated): Why is the second list item wrapped in `<p>` but the first isn't?

**Comment by probablyup** [comment]
> Sidenote (unrelated): Why is the second list item wrapped in <p> but the first instead?

Because of the newline between the second list item and perceived third one.

I'll take a look tomorrow if I have time. Probably just need to adjust the regex slightly to look for a space after the initial dash.

**Comment by probablyup** [comment]
Hmm I can't reproduce this. If you paste the content into the demo site, it is emitted correctly. Do you have another repro case?

**Comment by EvHaus** [comment]
My bad. Looks like this isn't an issue with `markdown-to-jsx`. I'm experiencing this issue with `react-styleguidist` which uses `markdown-to-jsx` under the hood, but after adding some tracing steps, it looks like there's a bug somewhere else that sends invalid markdown to the parser.

It seems when my file is loaded it sends the code as:

```
-   some
-   list

* * *
```

Will close this and track down what's causing this. Sorry for wasting your time.

**Comment by probablyup** [comment]
No time wasted, It's all good!
