### ISSUE TITLE
HR with spaces after a list is rendered as a list

### ISSUE THREAD

**Issue by sapegin** [probablyup/markdown-to-jsx#206]
This code renders `* * *` correctly, as an HR:

```md
-   one
-   two

Nope:

* * *
```

But this renders it as a list:

```md
-   one
-   two

* * *
```

![image 2018-08-17 at 1 33 34 pm](https://user-images.githubusercontent.com/70067/44264253-29486c00-a222-11e8-872b-e3d6c89bc3f2.png)

**Comment by probablyup** [comment]
Looking into it, but might be a bit difficult to fix. I'd recommend just leaving the spaces out between the asterisks for now.

**Comment by sapegin** [comment]
Remark adds them back ;-( But anyway I think it's pretty minor and there are workarounds (anything between the list and the line will fix it).

**Comment by probablyup** [comment]
Wait why are you using remark AND my component?

**Comment by sapegin** [comment]
We use it on the backend to do some transformations, like splitting text and code examples that we need to render as React components ;-)
