### ISSUE TITLE
Using non-breaking space &nbsp;

### ISSUE THREAD

**Issue by ahtohbi4** [probablyup/markdown-to-jsx#210]
@probablyup, thanks for the useful library!

How can I use [non-breaking space `&nbsp;`](https://en.wikipedia.org/wiki/Non-breaking_space) for formatting result text?

#### Now

If I try to write:

```markdown
<Markdown>
  {'# 10&nbsp;000')
</Markdown>
```
I get the next HTML:

```html
<h1>10&amp;nbsp;000</h1>
```

and result in browser:

> 10&amp;nbsp;000

#### Expected

```html
<h1>10&nbsp;000</h1>
```
> 10&nbsp;000

**Comment by probablyup** [comment]
https://shripadk.github.io/react/docs/jsx-gotchas.html#html-entities

see the second paragraph
