### ISSUE TITLE
Code tabulation in code blocks between HTML tags

### ISSUE THREAD

**Issue by AlexanderPrendota** [probablyup/markdown-to-jsx#211]
Hello @probablyup !

if i write example with some tabulation `\n`:

```md
<div class="markdown-to-jsx">
(\n) <-- MUST
`​`​`js
fun firstFunction(args: Array<String>) {
     print("Hello world")
}
(\n) <-- MUST (IMPORTANT TAB)
fun secondFunction() {
     print("Hello world")
}
`​`​`
(\n) <-- may be :) 
</div>
```

the code render without `IMPORTANT TAB`:
```md
<div class="markdown-to-jsx">

`​`​`js
fun firstFunction(args: Array<String>) {
     print("Hello world")
}
fun secondFunction() {
     print("Hello world")
}
`​`​`
</div>
```

I hope you can help!
Thanks!

**Comment by AlexanderPrendota** [comment]
@probablyup Could you take a look, please? 😔

**Comment by probablyup** [comment]
I can probably look this weekend. Sorry, work + the styled-components v4 beta has been keeping me busy.

**Comment by AlexanderPrendota** [comment]
@probablyup Thank you so much! 😊

**Comment by probablyup** [comment]
Give 6.7.3 a try, I think that fixes what you're referring to

**Comment by AlexanderPrendota** [comment]
Hello @probablyup ! Yep, it works on my side but still not working in your demo site. 
Awesome thanks for your help and for your best library! 😊
