### ISSUE TITLE
Cannot pass React.forwardRef directly

### ISSUE THREAD

**Issue by diegohaz** [probablyup/markdown-to-jsx#221]
I'm used to write overrides like this:
```js
const overrides = {
  h1: H1,
  h2: H2,
}
```

But since I started wrapping my components with `React.forwardRef` it didn't work anymore. I have to use the object version.

Reproduction: https://codesandbox.io/s/p7w1o7p4yx

**Comment by diegohaz** [comment]
@probablyup It doesn't seem to work. See https://codesandbox.io/s/p7w1o7p4yx

**Comment by probablyup** [comment]
Ok, I have an other idea.

**Comment by probablyup** [comment]
Fixed in 6.8.3 https://codesandbox.io/s/wq737kv2p7
