### ISSUE TITLE
Outermost wrapper

### ISSUE THREAD

**Issue by justrealmilk** [probablyup/markdown-to-jsx#223]
Reactive newbie here - I noticed that _ability to customize the outermost wrapper_ is on the roadmap but is there any way to achieve the same effect now?

**Comment by probablyup** [comment]
Not at the moment. What are you trying to do?

**Comment by justrealmilk** [comment]
i've been converting my jquery based portfolio to react and its powered by a headless cms which i use to output different arrangements of fields. the css relies on the parent wrapper being a div and all the consistency that comes with that so a <p> funks everything up

**Comment by probablyup** [comment]
You could [override](https://github.com/probablyup/markdown-to-jsx#optionsoverrides---override-any-html-tags-representation) the p tag and have it be a div instead. It's a little hacky but if you pass a known one-off prop to the `<Markdown>` wrapper and override `p` elements, you can look for the prop in your `p` override component and do something different for what ends up being the wrapper.

**Comment by justrealmilk** [comment]
Like I said, I'm not super confident in what I'm doing yet :P 

I did a bit of this 
```js
const captionDivs = ({ children, ...props }) => (
  <div {...props}>{children}</div>
);

            <Markdown
              options={{
                forceBlock: true,
                overrides: {
                  p: {
                    component: captionDivs,
                    props: {
                      className: 'caption margin markdown',
                    },
                  },
                },
              }}
            >
              { i.value.caption }
            </Markdown>
```

which works 90% of the time, and for the other 10%, i end up with a bunch of children to an empty `div`, where each paragraph is instead a `div`

**Comment by Finesse** [comment]
@probablyup Why not to just replace the top wrapping `div` with `React.Fragment`?

**Comment by probablyup** [comment]
React 15 doesn't have that and it wouldn't fix the OP's request

**Comment by probablyup** [comment]
Yes well the library supports 15 until the next major release.

**Comment by ckanthony** [comment]
@probablyup any updates on the proposal by @Finesse ?  it would be great if there is no wrapper.
