### ISSUE TITLE
Performance issue with br tag

### ISSUE THREAD

**Issue by sbondaryev** [probablyup/markdown-to-jsx#234]
Steps to reproduce
1. Go to: https://probablyup.com/markdown-to-jsx/
2. Replace content with (30 `<b>` tags):
```
<b>1</b><b>2</b><b>3</b><b>4</b><b>5</b><b>6</b><b>7</b><b>8</b><b>9</b><b>10</b>
<b>1</b><b>2</b><b>3</b><b>4</b><b>5</b><b>6</b><b>7</b><b>8</b><b>9</b><b>20</b>
<b>1</b><b>2</b><b>3</b><b>4</b><b>5</b><b>6</b><b>7</b><b>8</b><b>9</b><b>30</b>
```
3. Add `<br />` on top of this content

Browser freezes

**Comment by camistein** [comment]
I'm experiencing the same issue, could it be related to: https://github.com/probablyup/markdown-to-jsx/issues/136?

**Comment by probablyup** [comment]
Sorta... the regex for this HTML stuff is pretty intense
