### ISSUE TITLE
Double newlines required to get a newline within a block.

### ISSUE THREAD

**Issue by webpropopuli** [probablyup/markdown-to-jsx#235]
I have this text: 
```
"## MongoDB \n Our database is Mongo.  Simple and it plays well with json. \n\n This db is hosted at mLabs ."
```
The first `\n` works fine as it seems to separate the `<H2>` from the following paragraph, but _within_ the next block, I have to use a pair of `\n\n` to get the break.

I tried toggling `forceblock:` but no luck.

Maybe I'm misunderstanding something about something.

**Comment by probablyup** [comment]
https://daringfireball.net/projects/markdown/syntax#p :)

**Comment by webpropopuli** [comment]
Ugh, this is worse than that "spacing thing" in Python, but, yeah my bad. This is all MD weirdness, not your app. Thanks.
