### ISSUE TITLE
Extend `namedCodesToUnicode` with own/specific html codes

### ISSUE THREAD

**Issue by JeremiasEh** [probablyup/markdown-to-jsx#236]
Would it be possible to extend the `namedCodesToUnicode` constant with custom html codes to display them correctly.

Therefore a new `options.namedCodesToUnicode` object could integrated to extend the existing constant list while keeping the list in this repository as small/clean as it is at the moment.

```
options.namedCodesToUnicode = options.namedCodesToUnicode ? {...namedCodesToUnicode, ...options.namedCodesToUnicode} : namedCodesToUnicode;
```

```
…
.replace(HTML_CHAR_CODE_R, (full, inner) => {
              return options.namedCodesToUnicode[inner]
                ? options.namedCodesToUnicode[inner]
                : full;
            }),
…
```

The documentation could also be extended and the new options could work like this:

#### options.namedCodesToUnicode

By default only a couple of named html codes are converted to unicode characters.

* `&` (`&amp;`)
* `'` (`&apos;`)
* `>` (`&gt;`)
* `<` (`&lt;`)
* ` ` (`&nbsp;`)
* `"` (`&quot;`)

Some projects require to extend this map of named codes and unicode characters. To customize this list with additional html codes pass the option `namedCodesToUnicode` as object with the code names needed as in the example below:

```jsx
<Markdown options={{ namedCodesToUnicode: {
    le: '\u2264',
    ge: '\u2265',
} }}>This text is &le; than this text.</Markdown>;

// or

compiler('This text is &le; than this text.', namedCodesToUnicode: {
    le: '\u2264',
    ge: '\u2265',
});

// renders:

<p>This text is ≤ than this text.</p>
```

**Comment by probablyup** [comment]
Hmm yeah that seems reasonable if you'd like to send a PR
