### ISSUE TITLE
incorrect table rendering at first column in first row

### ISSUE THREAD

**Issue by simezi** [probablyup/markdown-to-jsx#241]
## issue

When I write table syntax, if the cell at first column in first row is empty
that cell is ignored and not rendered.

Thanks in advance.

### markdown code
```
|a|b|c|d|
| --- | --- | --- | --- |
|| bbb | ccc | ddd |
|| bbb | ccc | ddd |
```

###  what I expect to render
|a|b|c|d|
| --- | --- | --- | --- |
|| bbb | ccc | ddd |
|| bbb | ccc | ddd |

### what I actually get with markdown-to-jsx
|a|b|c|d|
| --- | --- | --- | --- |
| bbb | ccc | ddd ||
|| bbb | ccc | ddd |

This is reproduced when I paste the code into https://probablyup.com/markdown-to-jsx/

**Comment by probablyup** [comment]
Yikes, thanks for catching this
