### ISSUE TITLE
Question: does `markdown-to-jsx` have some events when markdown was rendered?

### ISSUE THREAD

**Issue by AlexanderPrendota** [probablyup/markdown-to-jsx#243]

**Comment by probablyup** [comment]
Nope, it just follows the typical render lifecycle like any other component. What are you trying to do?

**Comment by AlexanderPrendota** [comment]
...wanted to subscribe on...`componentDidMount()` =)

I have some components under "markdown" content and now it renders before "markdown" was converted to jsx and rendered on the page.  

Thanks :)

**Comment by probablyup** [comment]
Oh, just put the cDM above the `<Markdown>` component?
