### ISSUE TITLE
HTML multiline comments being rendered

### ISSUE THREAD

**Issue by eragon512** [probablyup/markdown-to-jsx#246]
Steps to reproduce:

* Go to the `markdown-to-jsx` demo page: https://probablyup.com/markdown-to-jsx/
* Replace the text with text containing a multiline HTML comment as follows:
```
Some text
<!-- This is a
multiline
comment -->
```

Expected output: 
```
Some text
```

Actual Output: 
```
Some text <!-- This is a multiline comment -->
```

**Comment by probablyup** [comment]
PR welcome!
