### ISSUE TITLE
highlight code syntax

### ISSUE THREAD

**Issue by marmikdesai** [probablyup/markdown-to-jsx#254]
Hi,

Is there way I can highlight code color?

Current Output
![image](https://user-images.githubusercontent.com/4994566/58539857-d3274100-8215-11e9-8eba-556c909dd748.png)

Desire Output
![image](https://user-images.githubusercontent.com/4994566/58539741-9b1ffe00-8215-11e9-820f-0303177fc2c8.png)

Marmik

**Comment by probablyup** [comment]
Pass a language type to your fenced code block and use highlightJS

**Comment by vikasaditya** [comment]
In reactMarkdown we are able to do this with    <ReactMarkdown source={input} renderers={{ code: CodeBlock }} /> where as CodeBlock is component that uses highlight.js.

Can we get an example on how you propose to use highlight or prism? 

Thanks.

**Comment by marmikdesai** [comment]
You can call this after your component render. 
Prism.highlightAll();

**Comment by smollweide** [comment]
Example with highlight.js:
https://stackblitz.com/edit/react-highlighted-markdown
