### ISSUE TITLE
Lists should not require blank line before them

### ISSUE THREAD

**Issue by mlkirkpatrick** [probablyup/markdown-to-jsx#256]
Often a list will have a block of text before it as a heading. Markdown-to-jsx seems to require a blank line between the text before it and the list itself. Using markdown-to-jsx, this:
```
Header:
* item 1
* item 2
```
Is rendered like this:
```
Header: * item 1 * item 2
```

Using the same block of text in Github's own markdown editor, this is what I get:

Header:
* item 1
* item 2

[John Gruber's markdown syntax guide](https://daringfireball.net/projects/markdown/syntax) doesn't give a hard rule about how this edge case should be handled. However, in testing other tools, markdown-to-jsx is the only one I've run into that seems to have this restriction. While all of them allow a blank line and that's fine, I'm of the opinion it shouldn't be _required_ since there is no spec to say it should be. A more flexible implementation is more user-friendly.

**Comment by oprobst-ethz** [comment]
I recognized that two consecutive lists with only one blank line cause trouble:

If you paste

```
1. Test
2. Test

- Item 1
- Item 2
```

into the front-end https://probablyup.com/markdown-to-jsx/ then the output is a bit unexpected.

**Comment by mlkirkpatrick** [comment]
In additional to lists, headings suffer from a similar issue. If a heading suffers follows regular text (or a list), it requires a blank line before the heading marker or it will not display correctly. You can have two headings back-to-back, though.

**Example:**
```
This is some text
## This is a heading
```

**Expected:**

> This is some text
> ## This is a heading

**Actual:**
> This is some text ## This is a heading

**Comment by yuankui** [comment]
how is it going?

**Comment by yuankui** [comment]
> how is it going?

If this issue is not going to be solved, I'll consider re-invent my wheels with prismjs

**Comment by Vadorequest** [comment]
I also need this, it's not user friendly when people are typing markdown by hand.

**Comment by SQReder** [comment]
Bump
