### ISSUE TITLE
Escaped pipes are ignored within table cells

### ISSUE THREAD

**Issue by robaxelsen** [probablyup/markdown-to-jsx#258]
Hi :wave: :smile:

I am running into this issue in Storybook, which uses markdown-to-jsx for markdown parsing: https://github.com/storybookjs/storybook/issues/6869

Could not find any issues here regarding this, so reporting it. Would it be possible to fix this? Thanks in advance for any help!

**Comment by probablyup** [comment]
Yeah, open to PRs 👍

**Comment by robaxelsen** [comment]
Looking deeper into this, I see the same output when parsing a table with escaped pipe characters with react-native-simple-markdown as well. And both seem to be built on top of simple-markdown. Will close this for now, and report there.

**Comment by probablyup** [comment]
Reopened - this library has diverged a lot from simple-markdown so good to fix this separately.

**Comment by robaxelsen** [comment]
> Reopened - this library has diverged a lot from simple-markdown so good to fix this separately.

@probablyup Ok, thanks. I tried to look into the code, but was not able to get the full picture. Would you be able to point me to any logic involved for this specific case, or hints on how you would go about making a fix for this?

Here is the new issue I created, which also mentions my crude test repo I've been playing with to solve this: https://github.com/robaxelsen/markdown-to-jsx-table-pipe-test

**Comment by probablyup** [comment]
I think probably here: https://github.com/probablyup/markdown-to-jsx/blob/master/index.js#L162

Checking and rejecting pipes that have an escape

**Comment by robaxelsen** [comment]
> I think probably here: https://github.com/probablyup/markdown-to-jsx/blob/master/index.js#L162
> 
> Checking and rejecting pipes that have an escape

@probablyup Thanks! I did some testing, and seems that line is used to match any line that is part of a table markdown.

This one seems promising though, as it's used throughout the code to split the row into cells, if I am reading the code correctly: https://github.com/probablyup/markdown-to-jsx/blob/5d4470314de8d652435e581851e4e8e2ef78a6c0/index.js#L174

Tried replacing it with regex that should ignore the newline, but having issues. Have any ideas?

Posted a relevant stackoverflow question here, which might help shed some more light on this: https://stackoverflow.com/questions/57306043/splitting-complex-string-with-while-ignoring-escaped-delimeter

**Comment by ariabuckles** [comment]
In `simple-markdown` I was able to fix this by actually parsing each row, rather than using `String.prototype.split`. The patch is here: https://github.com/Khan/simple-markdown/commit/f32a628401745787a2a199a5d3bde1efced4d6d5 , and I might try to see how hard it would be to do the same thing here.
