### ISSUE TITLE
"First argument must be a string" when receiving a string

### ISSUE THREAD

**Issue by itsthejoker** [probablyup/markdown-to-jsx#273]
Traceback:
```
esm.js?1aee:1 Uncaught (in promise) Error: markdown-to-jsx: the first argument must be
                             a string
    at compiler (esm.js?1aee:1)
    at Component.Markdown [as constructor] (esm.js?1aee:1)
    at Component.doRender [as render] (preact.js?10a9:229)
    at renderComponent (preact.js?10a9:271)
    at setComponentProps (preact.js?10a9:248)
    at buildComponentFromVNode (preact.js?10a9:339)
    at idiff (preact.js?10a9:134)
    at innerDiffNode (preact.js?10a9:176)
    at idiff (preact.js?10a9:152)
    at diff (preact.js?10a9:109)
```

I am a JS beginner, so apologies if there is an easy fix for this. I have a Preact project that I'm trying to render markdown on, and I'm passing a string in according to the documentation. I've performed the preact-compat redirect and other react packages are working as expected. Here is example code:

```
import {h, render} from 'preact';
import style from './style.scss';
import Markdown from "markdown-to-jsx";
import About from './about.md';

export default function AboutPage() {
    console.log(About);
    console.log(typeof (About));
    return (
        <div className={`${style.home} page`}>
            <Markdown children={About}/>
        </div>
    )
}
```

I have also tried `<Markdown>{About}</Markdown>` and `<Markdown>TEST STRING</Markdown>` but receive the same error.

**Comment by probablyup** [comment]
@itsthejoker interesting... if the second example you gave `<Markdown>TEST STRING</Markdown>` is giving that error there must be some unusual transpiling happening under the hood of your build system.

What is the output of `console.log(typeof (About));`?

**Comment by itsthejoker** [comment]
It outputs "string". In rerunning the second example, it still crashes, but I realized 1) the stack trace is slightly different and 2) I can expand the trace to get more information. Sorry about that. Below is the full traceback for `<Markdown>TEST</Markdown>`:

<details>

```
esm.js?1aee:1 Uncaught (in promise) Error: markdown-to-jsx: the first argument must be
                             a string
    at compiler (esm.js?1aee:1)
    at Component.Markdown [as constructor] (esm.js?1aee:1)
    at Component.doRender [as render] (preact.js?10a9:229)
    at renderComponent (preact.js?10a9:271)
    at setComponentProps (preact.js?10a9:248)
    at buildComponentFromVNode (preact.js?10a9:339)
    at idiff (preact.js?10a9:134)
    at innerDiffNode (preact.js?10a9:176)
    at idiff (preact.js?10a9:152)
    at innerDiffNode (preact.js?10a9:176)
```
Function | | File
-- | -- | --
compiler | @ | esm.js?1aee:1
Markdown | @ | esm.js?1aee:1
doRender | @ | preact.js?10a9:229
renderComponent | @ | preact.js?10a9:271
setComponentProps | @ | preact.js?10a9:248
buildComponentFromVNode | @ | preact.js?10a9:339
idiff | @ | preact.js?10a9:134
innerDiffNode | @ | preact.js?10a9:176
idiff | @ | preact.js?10a9:152
innerDiffNode | @ | preact.js?10a9:176
idiff | @ | preact.js?10a9:152
diff | @ | preact.js?10a9:109
renderComponent | @ | preact.js?10a9:293
renderComponent | @ | preact.js?10a9:284
rerender | @ | preact.js?10a9:39
Promise.then (async) |   |  
enqueueRender | @ | preact.js?10a9:35
setState | @ | preact.js?10a9:394
eval | @ | async.js?9f65:13
eval | @ | index.js?22c9:6
Promise.then (async) |   |  
load | @ | index.js?22c9:5
Async.componentWillMount | @ | async.js?9f65:12
setComponentProps | @ | preact.js?10a9:239
renderComponent | @ | preact.js?10a9:283
setComponentProps | @ | preact.js?10a9:248
buildComponentFromVNode | @ | preact.js?10a9:339
idiff | @ | preact.js?10a9:134
innerDiffNode | @ | preact.js?10a9:176
idiff | @ | preact.js?10a9:152
diff | @ | preact.js?10a9:109
renderComponent | @ | preact.js?10a9:293
setComponentProps | @ | preact.js?10a9:248
buildComponentFromVNode | @ | preact.js?10a9:339
idiff | @ | preact.js?10a9:134
diff | @ | preact.js?10a9:109
render | @ | preact.js?10a9:372
init | @ | entry.js?c83e:20
eval | @ | entry.js?c83e:25
../../../../../../../usr/local/lib/node_modules/preact-cli/lib/lib/entry.js | @ | bundle.js:823
__webpack_require__ | @ | bundle.js:708
fn | @ | bundle.js:113
0 | @ | bundle.js:1791
 __webpack_require__ | @ | bundle.js:708
(anonymous) | @ | bundle.js:806
(anonymous) | @ | bundle.js:809

**Comment by probablyup** [comment]
@itsthejoker any chance you can reproduce this in a codesandbox?

**Comment by itsthejoker** [comment]
The entire project was abandoned shortly after this issue occurred. We'll revisit it at some point, but until then we'll assume that it's a horribly-built environment and close the issue.
