### ISSUE TITLE
black / white lists or available tags / components

### ISSUE THREAD

**Issue by maksugr** [probablyup/markdown-to-jsx#274]
Hi!

I'm trying to find tool that will transform markdown (with custom jsx component) string from api to jsx. This tool is pretty go for it, thank you!

But I need to have posibility to control available tags / components that can be parsed by tool. Because I don't want my cms manager use all existing html tags.

Is it available with this tool? I didn't find it in documentation. Or may be it's good idea to have some option with array of available tags / components?

**Comment by SanichKotikov** [comment]
@maksugr you can try custom createElement function, for example like this:

```ts
const ALLOWED_TAGS = ['h2', 'p', 'strong', 'ul', 'ol', 'li'];

function createElement(type: any, props?: React.Attributes | null, children?: React.ReactNode) {
  return (typeof type === 'string' && ALLOWED_TAGS.includes(type))
    ? React.createElement(type, props, children)
    : React.createElement(React.Fragment, { key: props?.key }, children) as any;
}
```

**Comment by maksugr** [comment]
I think it will works for me. Thank you!
