### ISSUE TITLE
Array as props in React Component is rendered as a string

### ISSUE THREAD

**Issue by iamrane** [probablyup/markdown-to-jsx#275]
When I have this in my md

```
<MyCustomComponent ids={['test', 'with', 'an', 'array']} />
```

I get the ids prop as "['test', 'with', 'an', 'array']". So a string instead of an array.

Am I missing something?

**Comment by probablyup** [comment]
From the README:

> markdown-to-jsx also handles JSX interpolation syntax, but in a minimal
way to not introduce a potential attack vector. Interpolations are sent to
the component as their raw string, which the consumer can then eval() or
process as desired to their security needs.

**Comment by iamrane** [comment]
Ah! Thats good! Thank you!
