### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by probablyup** [probablyup/markdown-to-jsx#276]
Hey there! If you're a user of markdown-to-jsx and are interested in helping to maintain the library, I'd love your help! Unfortunately I don't have a lot of time for it these days...

I think realistically anyone can contribute to this project, but you'll probably want a solid knowledge of regex to be able to dive deep into the internals. There is very good test coverage to help prevent mistakes.

Reply below and I'll get back to you! Realistically, you should be willing to commit an hour or two a week to looking over issues, making changes, etc. The library is used in a lot of other toolchains, so this could be a nice resumé addition!

**Comment by probablyup** [comment]
cc @coreyward, you've shown a lot of interest in this lib 😄

**Comment by coreyward** [comment]
I’m open to the idea! I’d feel more confident if I had maybe a half hour of your time to walk me through some of the parsing logic (especially the weighting).

**Comment by ariabuckles** [comment]
@probablyup are you still looking for maintainers?

I'm the author/maintainer of simple-markdown and while I don't always have much time to offer (probably more on the order of a couple hours a month than a couple hours a week), I do:

 * have a vested interest in this project as one of the main usages of simple-markdown
 * have a solid knowledge of regular expressions (largely from writing simple-markdown) and am comfortable working in the codebase
 * have maintained simple-markdown & handled issues/improvements there for years

And I'd be happy to help maintain markdown-to-jsx as well!

**Comment by probablyup** [comment]
Hey Aria, definitely! As the original maintainer of the lib I forked from it makes a lot of sense for you to have some ownership over this one too if you're interested.

**Comment by probablyup** [comment]
I'll add a contributing md file so it's clear what the process is of cutting a new release, etc

**Comment by ariabuckles** [comment]
Thanks @probablyup ! That’d be super helpful!

**Comment by probablyup** [comment]
Done! https://github.com/probablyup/markdown-to-jsx/blob/master/CONTRIBUTING.md

**Comment by probablyup** [comment]
@coreyward I'd be happy to walk you through things as well if you're still interested.
