### ISSUE TITLE
Is there a way of opening all links in a new tab within options? 

### ISSUE THREAD

**Issue by SeanM96** [probablyup/markdown-to-jsx#286]

**Comment by SeanM96** [comment]
Closed, realised you can pass props to react components within overrides.

**Comment by prasanna3000** [comment]
Thanks, Saved my day!!

**Comment by mayanksolan** [comment]
if anyone need help on how to put this up - 
`options={{ overrides: { a: { props: { target: '_blank' } } } }}`
