### ISSUE TITLE
Prepend image src

### ISSUE THREAD

**Issue by tclayson** [probablyup/markdown-to-jsx#293]
I'm using a headless CMS which is sending markdown with relative image urls:

`![text](/uploads/8defb185f4c34e0281c100277b3a3777.jpg)`

Is there any way to get markdown-to-jsx to automatically prepend this image src? So that the resulting image tag is:

`<img src="https://cdn.mysite.com/uploads/8defb185f4c34e0281c100277b3a3777.jpg" />`

Thanks!

**Comment by probablyup** [comment]
You could override the img component and look at the src to conditionally
add the missing URL parts 👍

**Comment by tclayson** [comment]
Aha! Thanks so much! That was really easy in the end, thanks for the tip.

For anyone else who's struggling, here is the code I'm using:

```
const cdnHost = "https://cdn.myhost.com";

const Image = ({ src, ...props }) => (
  <img src={cdnHost + src} {...props} />
);

const options = {
  overrides: {
    img: { component: Image }
  }
};

// <Markdown options={options}>{richText}</Markdown>
```

Hope that helps someone!!!
