### ISSUE TITLE
Question about footnotes

### ISSUE THREAD

**Issue by colinricardo** [probablyup/markdown-to-jsx#295]
Does this project support footnotes? 

I have this: 
```
Here's a simple footnote,[^1] and here's a longer one.[^bignote]

[^1]: This is the first footnote.
```

and it renders as: 

![image](https://user-images.githubusercontent.com/21294951/77947729-46796380-72bc-11ea-943f-6785643b871f.png)

as compared with (from [here](https://www.markdownguide.org/extended-syntax/#footnotes)): 

![image](https://user-images.githubusercontent.com/21294951/77947832-690b7c80-72bc-11ea-8925-6124636488eb.png)

**Comment by csantos1113** [comment]
Yeah, it seems that the [regular expression to detect footnote references](https://github.com/probablyup/markdown-to-jsx/blob/master/index.js#L115) is failing in this case

**Comment by Andrewjeska** [comment]
Running into this as well

**Comment by csantos1113** [comment]
Here is the PR to fix this: https://github.com/probablyup/markdown-to-jsx/pull/304
