### ISSUE TITLE
About render LaTeX expression

### ISSUE THREAD

**Issue by DarkKris** [probablyup/markdown-to-jsx#298]
Is there any way to avoid rendering markdown syntax in Latex expressions?  

For example:   

```
$p_{u}^Tq_{v}$
```
will be rendered as:  

```html
p<em>{u}^Tq</em>v
```
'cause the ```_xxx_``` syntax in markdown. But what I want is a formula like ![image](https://user-images.githubusercontent.com/21234945/78746031-6255c700-7998-11ea-8fc3-ccb5c5c9b421.png)  

Thank you.

**Comment by probablyup** [comment]
You’ll want to use a code block for it and the provide an override “code”
component that applies whatever latex compiler you want

**Comment by DarkKris** [comment]
@probablyup 

thank you.
