### ISSUE TITLE
Configure Webpack with image support 

### ISSUE THREAD

**Issue by KamalAman** [probablyup/markdown-to-jsx#299]
In the Readme, is says you can configure Webpack with raw-loader to be able to load MD files as raw text. If you use the raw-loader, you loose out on local image support provided by the file-loader.

What is the proper configuration Webpack to load raw markdowns, but also get file-loader support?

It seems like I can get file support by using markdown-loader with the html-loader, however the markdown is parsed by the markdown-loader and messes up the formatting when used with markdown-to-jsx. 

I know this is not technically an issue with markdown-to-jsx, it is an infrastructure problem. Any advise would be helpful!

**Comment by probablyup** [comment]
You can specify what loaders you want to apply to the file when you import it using a syntax like this:

```js
import md from 'raw-loader!../myMDFile.md';
```
