### ISSUE TITLE
Allow only certain node types?

### ISSUE THREAD

**Issue by rgouni** [probablyup/markdown-to-jsx#318]
Hello,

Is there a way to only allow specific HTML tags in markdown? For example, I only want to allow links to be parsed in markdown, but nothing else. Is there a disabling/specifying allowed types feature available?

Something like `disallowedTypes` feature in [react-markdown](https://github.com/rexxars/react-markdown#options)

**Comment by probablyup** [comment]
Nothing specific, but you could add overrides for the elements you don't want and have them return `null`
