### ISSUE TITLE
Markdown not rendering, just showing file path

### ISSUE THREAD

**Issue by jackagolli** [probablyup/markdown-to-jsx#334]
Hi,

I may just be a React newbie, but I'm trying to render an external markdown file (.md).
I'm importing as follows:

`import post1 from './blog-post.1.md';`

and passing post1 as required into a Markdown component. However, I am just seeing the filepath and nothing rendered:
`/static/media/blog-post.1.f3a53693.md`

Is there something I'm doing wrong?

**Comment by probablyup** [comment]
Heya, please see the readme

**Comment by benwalk** [comment]
@jackagolli I was having this same issue and as a React newbie as well, I wanted to let you know I found [this medium post](https://medium.com/@shawnstern/importing-multiple-markdown-files-into-a-react-component-with-webpack-7548559fce6f) very helpful, particularly the link to [this thread](https://github.com/facebook/create-react-app/issues/2961#issuecomment-322916352) in explaining the issue. Hope that helps you! 

By the way, I read the entire readme and still couldn't figure out what was supposed to help in this case. :/

**Comment by coreyward** [comment]
@jackagolli  When you import a file using webpack the value of the variable is going to depend on the [loader](https://webpack.js.org/loaders/) used. In this case it sounds like your Markdown file is being handled by the file-loader, which is going to make sure your file makes it into the output and returns the path to the file as the variable. Instead you'll need to adjust your Webpack configuration to use the raw-loader which will return the data, or make a fetch request to the URL you have now to obtain the data to render.

**Comment by probablyup** [comment]
> By the way, I read the entire readme and still couldn't figure out what was supposed to help in this case. :/

https://github.com/probablyup/markdown-to-jsx#usage see the note that recommends using raw-loader

**Comment by saqi3492** [comment]
solution of this issue is mentioned here:
https://stackoverflow.com/questions/69032028/markdown-to-jsx-not-accepting-source/78415159#78415159
