### ISSUE TITLE
Does ~~strikethrough~~ work?

### ISSUE THREAD

**Issue by rscotten** [probablyup/markdown-to-jsx#335]
Hello,

Wondering if ~~Strikethrough~~ is supported, or if it's just not working for me?

I tried `~~Strikethrough~~` and it doesn't render like above.

**Comment by probablyup** [comment]
Hi @rscotten yes it does, you can try it on the live demo: https://probablyup.com/markdown-to-jsx/

**Comment by probablyup** [comment]
It renders as a `<del>` tag, so if you have a CSS reset that removes the default style for that element, it could be why you're not seeing the default visual.

**Comment by rscotten** [comment]
@probablyup  You're right, thank you!
