### ISSUE TITLE
[question] How to allow only several node types with less code?

### ISSUE THREAD

**Issue by xobotyi** [probablyup/markdown-to-jsx#343]
As i understand i can disable some nodes with help of `overrides` option by `null`ing the HTML tag, but what if i want to allow only several of them?

4ex: i want only to allow links, paragraphs, bold and italic. so if i got it right i should disable every other html tag in `overrides` option. It is extremely uncomfortable =\

How to it better way?

**Comment by canove** [comment]
Same here, I just need a few options enabled, is there a code snippet with all components overrides to null?

**Comment by canove** [comment]
I found this: https://github.com/probablyup/markdown-to-jsx/issues/328. 

Works great for me.
