### ISSUE TITLE
Paragraph tag adjacent to an img tag doesn't convert to custom component, any solution?

### ISSUE THREAD

**Issue by devavi-labs** [probablyup/markdown-to-jsx#345]
I am using this package for my blog page and I'm overriding all the html tags to be converted to my custom components, everything is being converted fine except one `<p>` tag which is just after an `<img>`  tag, I don't understand why is this happening. 

![Screenshot from 2020-11-11 23-15-41](https://user-images.githubusercontent.com/62388549/98845513-d8149a80-2473-11eb-8974-ab00fa981987.png)

![Screenshot from 2020-11-11 23-11-04](https://user-images.githubusercontent.com/62388549/98845525-dba82180-2473-11eb-909a-368f38f15add.png)

**Comment by devavi-labs** [comment]
![Screenshot from 2020-11-11 23-23-11](https://user-images.githubusercontent.com/62388549/98846357-f333da00-2474-11eb-9c3d-56d0e2a0bc1e.png)

**Comment by coreyward** [comment]
I've encountered this before, and from what I recall, it isn’t markdown-to-jsx creating the second, classless `<p>`, but instead the browser is doing so implicitly when it encounters the block-level `<div>` wrapping the `<img>` followed immediately by inline text.

**Comment by probablyup** [comment]
@devavi-labs if you could submit a failing a test I could use to work on a fix, that'd be great.

**Comment by devavi-labs** [comment]
okay I will do that

Avinash Kumar Sinha

**Comment by Ardhimas** [comment]
@coreyward I ran into this issue, took me a few hours to figure out that was the case. Is there a good workaround for it?

**Comment by coreyward** [comment]
@Ardhimas You might find some of the approaches in https://github.com/probablyup/markdown-to-jsx/issues/209 useful.
