### ISSUE TITLE
[Question] Is markdown parsed on the client?

### ISSUE THREAD

**Issue by zaydek** [probablyup/markdown-to-jsx#349]
Hey there, thank you for creating this repo!

I’m wondering when is markdown parsed? So specifically, if I’m using Next.js, does `markdown-to-jsx` parse markdown on the server or the client? And is this the same story for when using React.js?

Thank you!

**Comment by probablyup** [comment]
Both!

**Comment by zaydek** [comment]
Thanks for answering! Do you mind clarifying what you mean? Haha sorry I just didn’t get you.

Do you mean in Next.js markdown is parsed on the server and in React.js it’s parsed on the client?

**Comment by probablyup** [comment]
Yes, whatever runtime environment is running the JS will also parse the markdown.

**Comment by zaydek** [comment]
Bless you. Thanks! Closing.
