### ISSUE TITLE
Parser adding emphasis for the "b" in a_b_c

### ISSUE THREAD

**Issue by cheapsteak** [probablyup/markdown-to-jsx#352]
`a_b_c` is getting the `_b_` parsed as text with emphasis  

this makes `snake_cased_stuff` render as `snake<em>cased</em>stuff`

**Comment by probablyup** [comment]
This is the correct behavior per the markdown spec: https://daringfireball.net/projects/markdown/syntax#em

> Emphasis can be used in the middle of a word:
>
> un*frigging*believable

**Comment by laurentiu1981** [comment]
@probablyup is there any way to disable this when html is involved? For example `<span>snake_case_stuff</span>` would turn into `<span>snake<em>case</em>stuff</span>`.

The point of using `<Markdown>` wrapper is to be able to use snippets of html OR markdown in React, but if we have a mixture we end up with unexpected text displayed.
