### ISSUE TITLE
Ability to change wrapping tag. 

### ISSUE THREAD

**Issue by gaurangrshah** [probablyup/markdown-to-jsx#359]
I apologize if this is out-of-scope or context, but I am new to using markdown to render content. I noticed that my links are wrapped in a paragraph tag by default and am wondering if there was a way to override this behavior or skip it entirely? 

It may also be possible that I've missed something or am writing my markdown in some incompatible manner -- you can see my example below: 

Example:

This:
![image](https://user-images.githubusercontent.com/1086269/103255500-89ee2480-4957-11eb-96a8-c330b94e3793.png)

Compiles to this:
![image](https://user-images.githubusercontent.com/1086269/103255448-57dcc280-4957-11eb-83e0-b9d9549d6ca4.png)

Thanks in advance for any feedback!

**Comment by probablyup** [comment]
I believe the new functionality introduced in v7.1 is exactly what you're looking for https://github.com/probablyup/markdown-to-jsx/pull/268
