### ISSUE TITLE
Conditionally choosing which component to render.

### ISSUE THREAD

**Issue by gaurangrshah** [probablyup/markdown-to-jsx#360]
Firstly, id like to say thank you for your work, this library really simplified the amount if work I have to do to render markdown - and also for your prompt response on my previous issue. 

I understand that you've provided the ability to render elements with `createElement` using the built-in compiler, which works extremely well! 

I am wondering if there is a way to map conditionally chose which component is used to render each block within a markdown document?

```
<Markdown
        children={md}
        options={{
           React.Children.map(Child =>{
             if(Child.style.hasOwnPropery(fontWeight)){
                createElement(type, props, children) {
                   props.fontWeight = 600
                  return (
                    <div className="parent">
                      {React.createElement(Text, props, children)}
                    </div>
                 );
                }
               // or even better: // return <Text fontWeight={600}>Child</Text>
              } else {
                createElement(type, props, children) {
                  return (
                    <div className="parent">
                      {React.createElement(type, props, children)}
                    </div>
                 );
               }
            });
        }}
    />

```

I tried to do this myself without any luck, so I’m hoping this is something that is possible maybe with a different approach?

In either case thank you for your help once again! Really appreciate it!

**Comment by probablyup** [comment]
Honestly from that code snippet I don't really understand what you're trying to do, but you have a lot of freedom in the "overrides" functionality (see README) to customize how you render things.
