### ISSUE TITLE
Syntax Highlighting

### ISSUE THREAD

**Issue by timroty** [probablyup/markdown-to-jsx#367]
Has anyone been able to add syntax highlighting with this repository? I love this repo for adding custom components, but haven't figured out a reliable way to include custom automatic syntax highlighting. [https://github.com/remarkjs/react-markdown#use-custom-renderers-syntax-highlight](url) This repository lets you add custom renderers, but doesn't allow custom components as far as I'm aware. Is there a way to replicate this functionality with this implementation.

**Comment by stephan-noel** [comment]
I have, I opened the above PR explaining how to do this.  Also, it does allow custom components, [see the overrides option in the README](https://github.com/probablyup/markdown-to-jsx#optionsoverrides---rendering-arbitrary-react-components).
