### ISSUE TITLE
[Typescript] wrapper does not accept null

### ISSUE THREAD

**Issue by mjfwebb** [probablyup/markdown-to-jsx#375]
According to the recipe in the README, it says to set wrapper to null (https://github.com/probablyup/markdown-to-jsx#other-useful-recipes), but this is currently unsupported in the types.

Please see [this codesandbox](https://codesandbox.io/s/long-dream-uo1ur?file=/src/CustomMarkdown.tsx) which shows the error.

**Comment by probablyup** [comment]
Thanks for reporting, open to a PR if you'd like to take a stab at it!

**Comment by mjfwebb** [comment]
@probablyup PR submitted.

**Comment by mjfwebb** [comment]
Fixed in #380
