### ISSUE TITLE
img tag wrapped with p tag when i add some content

### ISSUE THREAD

**Issue by MustafaWael** [probablyup/markdown-to-jsx#383]
# when i add img tag  after another image or any html tag into <Markdown /> component will return the image wrapped with p tag

### example
```MDX
# Heading
![alt text](https://images.ctfassets.net/hrltx12pl8hq/7yQR5uJhwEkRfjwMFJ7bUK/dc52a0913e8ff8b5c276177890eb0129/offset_comp_772626-opt.jpg?fit=fill&w=800&h=300)
```

### return:
```HTML
<h1>Heading</h1>
<p>
  <img src='https://images.ctfassets.net/hrltx12pl8hq/7yQR5uJhwEkRfjwMFJ7bUK/dc52a0913e8ff8b5c276177890eb0129/offset_comp_772626-opt.jpg?fit=fill&w=800&h=300' alt='alt text'
</p>
``` 

### but expected return is:
```HTML
<h1>Heading</h1>
<img src='https://images.ctfassets.net/hrltx12pl8hq/7yQR5uJhwEkRfjwMFJ7bUK/dc52a0913e8ff8b5c276177890eb0129/offset_comp_772626-opt.jpg?fit=fill&w=800&h=300' alt='alt text'
```

**Comment by MaximPetrichuk** [comment]
The same problem, with custom override img tag in console warning message: Expected server HTML to contain a matching <div> in <p>.

**Comment by CurtisMac** [comment]
This is also an issue for me as I'm replacing the img with GatsbyImage component which uses <div> tags

**Comment by probablyup** [comment]
Inline content should be wrapped in a paragraph, I won't be changing this in the library sorry.
