### ISSUE TITLE
Version 7.1.5 is not compatible with IE 11

### ISSUE THREAD

**Issue by egauci** [probablyup/markdown-to-jsx#415]
I don't know about 7.1.4 since I upgraded from 7.1.3. There is at least one arrow function in the distributed code.

I understand that IE 11 is fast dying, but I have to support it for a bit longer. Also I feel it is inappropriate to make such a change in a patch release.

This isn't urgent for me. Version 7.1.3 is working well. Mostly I entered this in case you didn't know.

**Comment by probablyup** [comment]
Hmm wasn’t intentional, this should be fixed for v7 and we’ll drop IE11 support for v8

**Comment by probablyup** [comment]
I don't see this in 7.x latest, closing
