### ISSUE TITLE
Multiple line breaks are not preserved

### ISSUE THREAD

**Issue by DoneDeal0** [probablyup/markdown-to-jsx#420]
Hello,

The component doesn't preserve multiple line breaks. 

Example:
```js
import Markdown from "markdown-to-jsx";

const content = `hello world

this is very




spaaaaaacy!!!
`
export default function App() {
  return (
    <div>
     <Markdown options={{ forceBlock: true }} children={content} />
    </div>
  );
}

```

current redering:
```js
hello world

this is very

spaaaaaacy!!!
```

expected rendering:

```js
hello world

this is very




spaaaaaacy!!!
```

EDIT: I just added a function to insert br on line break, now it works, sorry.

**Comment by vileen** [comment]
@DoneDeal0 

> I just added a function to insert br on line break, now it works, sorry.
 how did you do it though?
