### ISSUE TITLE
Parsing error on `[h]:m` string

### ISSUE THREAD

**Issue by whytspace** [probablyup/markdown-to-jsx#456]
First a huge thanks for providing this library. It has made using markdown in react a breeze. 👍 

Recently we discovered an issue with one of our users posting a cell formating string for Excel: `[h]:mm;@`
(Yes, I know that things like this should be wrapped inside a code block, but regular users just don't do that)

We were using a slighly outdated version (`7.1.5`) that threw an error in the console:
`React.cloneElement(...): The argument must be a React element, but you passed null.`

We were able to reprodice the problem locally. When passing `[h]:m` to the `<Markdown>` component, it fails to parse the string.

Noticing that we were not on the latest version (`7.1.7` as of writing this) we immediately updated to the latest version, which "fixed" the issue, **but `[h]:m` still cannot be parsed, it is now simply omitted from the output.**

### Example

Input: `hello [h]:m **world**`
Output: `hello <strong>world</strong>`
Expected output: `hello [h]:m <strong>world</strong>`

Here is a sandbox with a reproduction: https://codesandbox.io/s/dark-rgb-fonbki

I was expecting to just get the plain text returned when the word is not any kind of markdown syntax.
Am I missing something? Is `[h]:m` matching some markdown syntax that I am not familiar with?

**Comment by probablyup** [comment]
Will take a look

**Comment by probablyup** [comment]
In this case the code in question is being identified as a _reference_, per the [markdown spec](https://daringfireball.net/projects/markdown/syntax): 

> Then, anywhere in the document, you define your link label > > like this, on a line by itself:
>
> ```
> [id]: http://example.com/  "Optional Title Here"
> ```

**Comment by probablyup** [comment]
Although I just noticed a detail that was missed before:

> That is:
> 
> Square brackets containing the link identifier (optionally > indented from the left margin using up to three spaces);
> followed by a colon;
> **followed by one or more spaces (or tabs);**
> followed by the URL for the link;
optionally followed by a title attribute for the link, enclosed in double or single quotes, or enclosed in > parentheses.

Will ensure we're handling this case properly!

**Comment by probablyup** [comment]
Fixed in 7.1.8
