### ISSUE TITLE
GFM Tasks seem to be broken

### ISSUE THREAD

**Issue by himbolion** [probablyup/markdown-to-jsx#481]
I was trying out random Markdown things and noticed that the Task list provided by this Module doesn't work

From my testing it seems like the regex for this should be `^-\s*?\[(x|\s)\]`, since we're expecting a dash before the box

**Comment by probablyup** [comment]
Mind submitting a PR?

**Comment by probablyup** [comment]
Double checked and we have tests that specifically verify the GFM setup and can confirm it works as expected on the demo site. Going to close this, if you have a specific reproduction that would be helpful!
