### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by pateljay1397** [probablyup/markdown-to-jsx#487]
I am using the following component **MarkdownJsx** to render the readme of my application. So in my readme, if add self-closingI(<br/>) tags as a regular tag(<br></br>), It crashes the application to handle the error thrown by MarkdownJsx, I added try-catch but it doesn't go to catch block and crashes the application. Is there a way by which we can handle the error thrown by MarkdownJsx while rendering the readme file?

FYI: Following are self-closing tags. https://developer.mozilla.org/en-US/docs/Glossary/Void_element

**Comment by stevemckenzie** [comment]
I'm seeing this issue as well. Did you find a workaround?

**Comment by pateljay1397** [comment]
We wrapped the <MarkdownJsx> component with React Error Boundary component. and added a override to 
`<MarkdownJsx options={mergedOverridesOptions} >{children} </MarkdownJsx>
const selfClosingTags = { br: () => <br />, col: () => <col />, hr: () => <hr />, wbr: () => <wbr /> }
const mergedOverridesOptions = Object.assign({}, options, { overrides: Object.assign({}, options?.overrides, selfClosingTags) });
`
