### ISSUE TITLE
table with <ol> or <ul> tags.

### ISSUE THREAD

**Issue by huggie1984** [probablyup/markdown-to-jsx#488]
Hi, thank for the great package.

Seems i am having an issue rendering content in a table using v6 +

When rendering the following into a table:

```
|  |  |  |
| ---------- | ---------- | ---------- |
| __title__ | <ul><li> a really really really really long list item 1</li><li> a really really really really long list item 1</li></ul> | [Get in touch with us](https://soime url"Understanding your needs") |
```

The markdown after the list items are not parsed correctly.

<img width="1416" alt="image" src="https://user-images.githubusercontent.com/4369556/229756015-f6378c6a-a63c-4210-acfe-6db7f448d6b2.png">

**Comment by probablyup** [comment]
Interesting, can confirm it on the demo site

**Comment by gusbmurphy** [comment]
Hi @probablyup and @huggie1984, I've just started to look into this issue, and it seems like there's actually an issue where any HTML elements with more than one level of depth will prevent markdown syntax from being parsed in subsequent columns of a table. Here's an example I came up with:

```
| Column A                              | Column B                 |
| ------------------------------------- | ------------------------ |
| <div><div>I'm in column A</div></div> | **Hello from column B!** |
```

And a screenshot on the example site:
<img width="976" alt="Screenshot 2023-07-01 at 6 21 09 PM" src="https://github.com/probablyup/markdown-to-jsx/assets/50927042/41915710-47fc-4631-841d-7ddfeae0d5cc">

I'll continue playing around with this and see if I can find a solution, but just wanted to share this.

**Comment by gusbmurphy** [comment]
Created a PR that (I believe) fixes this issue. One thing I wanted to point out is that in the original example there is actually a syntax error in the given markdown. The link in the third column is malformed: `[Get in touch with us](https://soime url"Understanding your needs")`, the `"Understanding your needs"` might be a type or something. Replacing that with a correctly formed link still produces the issue.
