### ISSUE TITLE
cannot use import statement outside a module

### ISSUE THREAD

**Issue by alexander-entin** [probablyup/markdown-to-jsx#495]
When used in Rakkas.

Adding `"type": "module"` to `node_modules/markdown-to-jsx/package.json` helped

**Comment by greypants** [comment]
Same issue using this in Vite + vite-plugin-ssr and same thing fixes it: Adding `"type": "module"` to `node_modules/markdown-to-jsx/package.json` also fixed it for me. 

Removing the conditional exports also fixes it for me, but that's probably not what we want here.

**Comment by greypants** [comment]
I don't fully understand what the right package.json configuration is... I tried making the suggested change in #498, but the build failed. 

I Just swapped this package for https://github.com/remarkjs/react-markdown for the time being, which builds fine.

**Comment by nbarrow-inspire-labs** [comment]
Also experiencing this issue. Any timeline on a fix?
