### ISSUE TITLE
Override code block

### ISSUE THREAD

**Issue by mshaaban0** [probablyup/markdown-to-jsx#98]
This is pretty cool 👍 
I am trying to override the `code` blocks in markdown, but i need the value of that code block to be passed in a prop for a component. is that possible ?

```
<Markdown 
    options={{
        overrides: {
            code: {
                  component: AceEditor,
                      props: {
                          height: '6em',
                          mode:'jsx',
                          value: 'CODE VALUE GOES HERE'
                      }
                  }
             }
         }}>
    {zComponents['readme']}
</Markdown>
```

**Comment by probablyup** [comment]
Haven't tried this, but what if you change "value" to "children"?

**Comment by mshaaban0** [comment]
`AceEditor` it's a third party dependency, doesn't support that.

**Comment by mshaaban0** [comment]
That would be cool i guess, i'll try to open a PR
```
overrides: {
    code: (val) => {
        // Whatever
    }
}
```

**Comment by probablyup** [comment]
I think I understand now. Here's what I would suggest: make an interim component that translates normal JSX into the format that AceEditor needs. For example:

```jsx
const CodeToAceEditor = (props) => (
    <AceEditor
        height="6em"
        mode={props.className.replace('lang-', '')}
        value={props.children}
    />
);
```

And feed that in as an override:

```js
overrides: {
    code: {
        component: CodeToAceEditor,
    }
}
```

**Comment by mshaaban0** [comment]
👍 perfect, appreciate the help. thanks

**Comment by prmichaelsen** [comment]
Hey, as a follow up, this works for `codeBlock` but breaks `codeInline`. Would it be possible to add the ability to override each parsed type, ie, `codeBlock` and `codeInline` separately, as opposed to the rendered HTML? Or does this feature already exist and I am just missing it?
